Rf/fix/explorer urls v2
infinitybase/bako-safe-ui pull request #485
Opened 2024-10-08 21:18 UTC by RafaDev95

2024-10-08 23:21 UTC, luisburigo requested changes

2024-10-08 23:21 UTC, luisburigo commented on src/modules/transactions/components/TransactionCard/DetailsDialog.tsx
> +      `${findNetworkByUrl(network.url).explorer}/tx/0x${hash}`,
prevent reference error on network not inserted in storage

```ts
const handleViewInExplorer = () => {
    const { hash, network } = transaction;
    const networkInfo = findNetworkByUrl(network.url);
    
    if(networkInfo) {
      window.open(
        `${networkInfo.explorer}/tx/0x${hash}`,
        '_BLANK'
      );
    }
```

2024-10-08 23:21 UTC, luisburigo requested changes

2024-10-08 23:21 UTC, luisburigo commented on src/modules/transactions/components/TransactionCard/deposit-details/DepositDetails.tsx
> +      `${findNetworkByUrl(network.url).explorer}/tx/0x${hash}`,
https://github.com/infinitybase/bako-safe-ui/pull/485#discussion_r1792609911

2024-10-08 23:21 UTC, luisburigo commented on src/modules/vault/components/box/index.tsx
> +      `${findNetworkByUrl(network.url).explorer}/account/${address}/assets`,
https://github.com/infinitybase/bako-safe-ui/pull/485#discussion_r1792609911

2024-10-08 23:21 UTC, luisburigo commented on src/modules/transactions/providers/toast.tsx
> +      `${findNetworkByUrl(networkUrl).explorer}/tx/0x${hash}`,
https://github.com/infinitybase/bako-safe-ui/pull/485#discussion_r1792609911

2024-10-08 23:23 UTC, luisburigo requested changes

2024-10-08 23:23 UTC, luisburigo commented on src/modules/transactions/components/TransactionCard/Details.tsx
> +      `${findNetworkByUrl(network.url).explorer}/tx/0x${hash}`,
https://github.com/infinitybase/bako-safe-ui/pull/485#discussion_r1792609911

2024-10-09 09:24 UTC, guimroque commented on src/modules/network/services/methods.ts
>  };
we have an default return, `findByNetwork` will never return undefined

2024-10-09 09:24 UTC, guimroque commented on src/modules/network/services/methods.ts
>  };
@luisburigo

2024-10-09 16:55 UTC, guimroque approved these changes

2024-10-09 16:55 UTC, merged